import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../../api/client";
import StatusBadge from "../../components/StatusBadge";
import Modal from "../../components/Modal";

const EMPTY = { customerName: "", customerPhone: "", address: "", serviceTypeId: "", serviceItem: "", brand: "", complaint: "", scheduledDate: "" };

export default function MyOrders() {
  const [orders, setOrders] = useState([]), [serviceTypes, setServiceTypes] = useState([]), [loading, setLoading] = useState(true), [modalOpen, setModalOpen] = useState(false), [form, setForm] = useState(EMPTY), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const navigate = useNavigate();
  async function load() { setLoading(true); try { setOrders((await api.get("/my/orders")).data); } finally { setLoading(false); } }
  useEffect(() => { load(); api.get("/service-types").then(({ data }) => setServiceTypes(data.filter((s) => s.isActive))); }, []);
  const active = orders.filter((o) => !["DONE", "INVOICED", "CANCELLED"].includes(o.status));
  const finished = orders.filter((o) => ["DONE", "INVOICED", "CANCELLED"].includes(o.status));
  async function submit(e) { e.preventDefault(); setSaving(true); setError(""); try { const { data } = await api.post("/my/orders", form); setModalOpen(false); await load(); navigate(`/my/orders/${data.id}`); } catch (err) { setError(err.response?.data?.error || "Gagal membuat order"); } finally { setSaving(false); } }
  const card = (o, faded = false) => <div key={o.id} className="card" style={{ padding: faded ? "10px 16px" : 16, cursor: "pointer", opacity: faded ? 0.75 : 1 }} onClick={() => navigate(`/my/orders/${o.id}`)}><div style={{ display: "flex", justifyContent: "space-between", gap: 10, marginBottom: 6 }}><span className="mono" style={{ fontSize: 12.5, color: "var(--text-muted)" }}>{o.orderNumber}</span><StatusBadge status={o.status} /></div><div style={{ fontSize: 14.5, fontWeight: 500 }}>{o.customer?.name}</div><div style={{ fontSize: 13, color: "var(--text-muted)" }}>{o.serviceType?.name}</div><div style={{ fontSize: 12.5, color: "var(--text-faint)", marginTop: 4 }}>{o.address}</div></div>;
  return <div className="technician-orders"><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 20 }}><div><h1 style={{ fontSize: 19, marginBottom: 4 }}>Order Saya</h1><p style={{ color: "var(--text-muted)", fontSize: 13, margin: 0 }}>Tugas yang ditugaskan kepada kamu</p></div><button className="btn btn-primary" onClick={() => { setForm(EMPTY); setError(""); setModalOpen(true); }}>+ Order Baru</button></div>{loading && <div style={{ color: "var(--text-muted)" }}>Memuat...</div>}{!loading && <><div style={{ display: "flex", flexDirection: "column", gap: 10 }}>{active.length ? active.map((o) => card(o)) : <div className="card" style={{ padding: 16, color: "var(--text-faint)" }}>Tidak ada order aktif saat ini.</div>}</div>{finished.length > 0 && <><h3 style={{ fontSize: 13.5, color: "var(--text-muted)", marginTop: 26, marginBottom: 10 }}>Selesai / Ditagihkan</h3><div style={{ display: "flex", flexDirection: "column", gap: 8 }}>{finished.map((o) => card(o, true))}</div></>}</>}<Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Order Baru dari Lapangan"><form onSubmit={submit} style={{ display: "flex", flexDirection: "column", gap: 12 }}><div style={{ fontSize: 12.5, color: "var(--text-muted)" }}>Order otomatis ditugaskan ke akun Anda.</div><input placeholder="Nama pelanggan" value={form.customerName} onChange={(e) => setForm({ ...form, customerName: e.target.value })} required /><input type="tel" inputMode="tel" placeholder="Nomor WhatsApp pelanggan" value={form.customerPhone} onChange={(e) => setForm({ ...form, customerPhone: e.target.value })} required /><textarea placeholder="Alamat lengkap servis" rows={2} value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} required /><select value={form.serviceTypeId} onChange={(e) => setForm({ ...form, serviceTypeId: e.target.value })} required><option value="">Pilih layanan</option>{serviceTypes.map((s) => <option key={s.id} value={s.id}>{s.code} — {s.name}</option>)}</select><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><input placeholder="Unit (mis. AC 1 PK)" value={form.serviceItem} onChange={(e) => setForm({ ...form, serviceItem: e.target.value })} /><input placeholder="Merk" value={form.brand} onChange={(e) => setForm({ ...form, brand: e.target.value })} /></div><textarea placeholder="Keluhan pelanggan" rows={2} value={form.complaint} onChange={(e) => setForm({ ...form, complaint: e.target.value })} /><input type="date" value={form.scheduledDate} onChange={(e) => setForm({ ...form, scheduledDate: e.target.value })} />{error && <div style={{ color: "var(--signal-red)", fontSize: 13 }}>{error}</div>}<button className="btn btn-primary" style={{ justifyContent: "center" }} disabled={saving}>{saving ? "Menyimpan..." : "Buat & Buka Order"}</button></form></Modal></div>;
}
